# Generated by Django 6.0.1 on 2026-02-03 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("recorded_at", models.DateTimeField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("segment_order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["conversation", "segment_order"],
            },
        ),
        migrations.CreateModel(
            name="ImprovementNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("filler_word", "Filler Word"),
                            ("confidence", "Confidence"),
                            ("tone", "Tone"),
                            ("pace", "Pace"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feedback_text", models.TextField()),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="1=low, 5=high", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_notes",
                        to="conversations.transcriptsegment",
                    ),
                ),
            ],
            options={
                "ordering": ["segment", "note_type"],
            },
        ),
        migrations.AddConstraint(
            model_name="transcriptsegment",
            constraint=models.UniqueConstraint(
                fields=("conversation", "segment_order"),
                name="unique_segment_order_per_conversation",
            ),
        ),
    ]
