# Generated by Django 6.0.1 on 2026-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptsegment",
            name="speaker_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="From diarization (e.g. Speaker A); empty for non-WhisperX segments.",
                max_length=64,
            ),
        ),
    ]
